### ISSUE TITLE
Can not remap localleader?

### ISSUE THREAD

**Issue by Cutuchiqueno** [vim-pandoc/vim-pandoc#153]
I tried to remap localleader in my main `.vimrc` as well as in `after/ftplugin/pandoc.vim` but it shows now effect. `:nnoremap` still enlist `\` for all vim-pandoc key-bindings.

The mapping I use is:

```
let maplocalleader="\<SPACE>"
```

**Comment by viniciusarcanjo** [comment]
I'm running neovim 0.1.7 and I don't have any issues with mapping my localleader. In fact, I have leader and localleader mapped to different keys and they work as expected.

```
  let mapleader="\<Space>"
  let maplocalleader=","
```
Could you double check your vimrc?

**Comment by victorkristof** [comment]
@Cutuchiqueno Try to use `:verbose nnoremap` to see where the mappings are defined.

I had a similar problem. In my case it was because I was saving views using `mkview` with default `'viewoptions'`, _which includes saving mappgins through its `options` argument_. I had changed my localleader after saving the view, which was loaded every time and hence re-setting the pandoc mappings to the old localleader.

Removing the content of `~/.vim/view/` and setting `set viewoptions-=options` in my `.vimrc` did the trick.

**References**:
```
:h 'viewoptions'
:h :mkview
```
