### ISSUE TITLE
disable chdir module by default

### ISSUE THREAD

**Issue by Konfekt** [vim-pandoc/vim-pandoc#272]
The `chdir` module should be opt-in and not opt-out as it catches the user by surprise.

Likewise, `[ 'menu', 'keyboard', 'spell']` are debatable. The user should know that they exist before they are enabled.

**Comment by Konfekt** [comment]
That is, instead of a module `chdir` enabled by default, add a FAQ entry:

Q: On opening a `pandoc` file the current work dir is not that of the file, what's wrong?

A: Add to `vimrc` the line
```vim
autocmd FileType pandoc :lchdir %:p:h
```

And instead of a module `spell`, enabled by default, add a FAQ entry:

Q: On opening a `pandoc` file the spell check is not enabled, what's wrong?

A: Add to `vimrc` the line
```vim
autocmd FileType pandoc setlocal spell
```

**Comment by randomizedthinking** [comment]
First, thanks for the nice plugin.

Recently I switched from `vim-markdown` to `vim-pandoc`, and was bite by this issue. I also tend to think, it is better not to change root directory automatically.

**Comment by alerque** [comment]
I completely agree. I've been bitten by this too and the behavior is completely surprising. It also throws off a lot of other plugins and workflows that assume the CWD is maintained as the project level and operate on everything under it.

**Comment by fmoralesc** [comment]
I remember adding this because I got bit by not changing the directory to the current one many times. I assumed this would be a pain point for many others (all things considered, I've received relatively few complaints about this, so it might still be a reasonable call). `vim-pandoc` is purposefully maximalist so that setup for the general cases is minimal, while still allowing some flexibility. So that's the reason why `chdir` was there. 

Having said that, I concede the point. I can see how this will be disruptive for some workflows (you can see a bias towards my own, where the document *is* the project). In any case, have additional configuration to handle this in the general case that is more flexible than the `autochdir` setting (https://github.com/fmoralesc/vim-extended-autochdir), so I won't necessarily miss the module.

Adding a note to the documentation is a good idea. I like @Konfekt's [wording in his comment(https://github.com/vim-pandoc/vim-pandoc/issues/272#issuecomment-400980783)] above.
