### ISSUE TITLE
I don't know how it works, please help

### ISSUE THREAD

**Issue by NatalieGates** [vim-pandoc/vim-pandoc#295]
Hello - 

I installed successfully with vundle but I am not able to get this to work. In sublime text I edit the settings file to point to my bib file and when I type @ I receive authors and titles to choose from. 

I'm not sure what to do to set this up. If someone can give me step-by-step instructions I would be very grateful.

**Comment by fmoralesc** [comment]
OK. So the configuration depends a little bit on how you have your projects set up. From what I gather, you want to make the completion work, so let's focus on that.

1) First, check if the plugin is loading properly. If you open a *.md file, it should set the fileytype to `pandoc` (not markdown)
```
:echo &filetype
```
should print `pandoc` to the status bar. You will need python support for most things, so check that
```
:echo has('python')
```
prints 1.

2) Now, if you have a bibliography file in the same folder as the file you are working on, vim-pandoc should detect that automatically by default. Otherwise, you can configure it like this:
```
leg g:pandoc#biblio#bibs = ['mypath1', 'mypath2']
```
You put this in your .vimrc or init.vim file.

3) If you configured `g:pandoc#biblio#bibs`, you'll need to `:source` your vimrc, and reopen the file (just the first time).

4) If everything goes well, you should be able to complete bibliographical references by pressing `<Control>X<Control>O` after a `@` or a partial name. That should look like this:
![Screenshot from 2019-03-09 22-07-15](https://user-images.githubusercontent.com/221465/54077383-be42ad80-42b7-11e9-942d-38afb9c21dce.png)

5) Then you can complete the items with Enter.

I hope this helps. Feel free to ask.

**Comment by NatalieGates** [comment]
Thanks so much, it worked. I just need to add:

`leg g:pandoc#biblio#bibs = ['mypath1', 'mypath2']`

as you suggested, and it worked!

Thanks!

**Comment by fmoralesc** [comment]
Good to hear!
