### ISSUE TITLE
This plugin causes markdown files to open slowly

### ISSUE THREAD

**Issue by NatalieGates** [vim-pandoc/vim-pandoc#297]
This plugin causes `.md` files to open slowly. Is this expected behavior or is there a solution?

**Comment by fmoralesc** [comment]
Hi! The plugin does a lot every time a markdown file is opened, so it can slow things down. It will depend on  the file, however. Do you have examples? While some slowness is possible and to be expected, it shouldn't be too much, otherwise it could indicate some trouble (it's hard to know where without more information).

**Comment by NatalieGates** [comment]
thank you for the quick response. it's a 80,000 word document... usually it's much more responsive... but this one file I do not want to break into pieces.
