### ISSUE TITLE
pandoc is overwriting movement remappings

### ISSUE THREAD

**Issue by h8ed** [vim-pandoc/vim-pandoc#299]
Basically, a bit ago I remapped the default `h j k l` movement keys to `j k l ;` (capital versions as well). So I'm not losing any keys I mapped `h` to `:` and `H` to `;`. It's going pretty good so far. The only things is that I've pinpointed vim-pandoc to be the cause of a bug, in which when editing a markdown or Rmarkdown file, all the mappings are not respected. `l`, `h` and `;` work as I mapped them but `j` and `k` revert to the default vim mappings, so basically I have `down, up, up, right` movements only, making editing markdown files practically impossible. Any insight as to why this could be? Is there a way to counteract this without too much work?

Here is the relevant part of my .vimrc:
```vim
noremap j h
noremap k j
noremap l k
noremap ; l

noremap J H
noremap K J
noremap L K
noremap : L

noremap h :
noremap H ;
```

Here is the output of...
`:verbose noremap j`:
```
v  j           *@gj
Last set from ~/.config/nvim/plugged/vim-pandoc/autoload/pandoc/keyboard.vim

n  j           *@gj
Last set from ~/.config/nvim/plugged/vim-pandoc/autoload/pandoc/keyboard.vim

o  j           * h
Last set from ~/.config/nvim/init.vim

v  j           * h
Last set from ~/.config/nvim/init.vim

n  j           * h
Last set from ~/.config/nvim/init.vim
```
`verbose noremap k`:
```
v  k           *@gk
Last set from ~/.config/nvim/plugged/vim-pandoc/autoload/pandoc/keyboard.vim

n  k           *@gk
 Last set from ~/.config/nvim/plugged/vim-pandoc/autoload/pandoc/keyboard.vim

o  k           * j
Last set from ~/.config/nvim/init.vim

v  k           * j
Last set from ~/.config/nvim/init.vim

n  k           * j
Last set from ~/.config/nvim/init.vim
```
(slightly edited for readability) Higher = more recent apparrently ¯\_(ツ)_/¯

Any help is appreciated

**Comment by alerque** [comment]
It looks like this is going to have to do with `vim-pandoc`'s use of _conceal_ features in vim. It appears to be remapping motion keys such as `j` to `gj` which is to move one **visible** character instead of one actual byte in the source. This allows the motion keys to skip over things that have been concealed.

**Comment by fmoralesc** [comment]
That is indeed the solution. Note that this is the default not because of the use of conceals, but because in soft wrapping mode it is a bit of a pain to skip visible lines when using  `j` and `k` (not that there aren't many other more efficient ways to move around).

In any case, I think we have to make a note of this in the documentation about the keyboard module in soft wrapping mode.

**Comment by h8ed** [comment]
Hmm.. for some reason when I set `:set g:pandoc#keyboard#display_motions == 0`
I get `Unknown option: g:pandoc#keyboard#display_motions`

**Comment by fmoralesc** [comment]
You have to use `=` instead of `==`. I edited @alerque's comment to reflect this.

**Comment by alerque** [comment]
@h8ed My bad, use `let` not `set`.

**Comment by h8ed** [comment]
Alright, it works! Thank you both.

**Comment by fmoralesc** [comment]
Just added some documentation for this. Closing ;)
