### ISSUE TITLE
pandoc-execute opens a terminal buffer in neovim

### ISSUE THREAD

**Issue by fflores97** [vim-pandoc/vim-pandoc#310]
Hi,

Today vim-pandoc started opening a terminal buffer (named `pandoc-execute`) when using `:Pandoc`. Previously a window like this only opened when there was a compilation error, but now it's happening every time and it's quite distracting when writing. I have reinstalled neovim and the python modules and it still happens. I have also set `g:pandoc#modules#warn_disabled = 0` and `g:pandoc#command#use_message_buffers = 0`

**Comment by fmoralesc** [comment]
I changed this because I decided that the method that we used for handling pandoc's output was error prone and wasn't helpful when using pandoc wrappers like panzer et al (for example, in many cases one would not ever get output on errors, which was frustrating when things went badly.) Always showing the output of 

I will look into making it optional, though, or at least more discrete (for example, by reducing the height of the window).

**Comment by fflores97** [comment]
Cool cool, I just thought for a moment that I'd messed something up. Thanks for the quick reply!

**Comment by alerque** [comment]
@fflores97 I think we can keep this issue open to track how it is addressed. If/when there is a configuration option for this or a change to the default size we'll report it here, then close it as resolved.

**Comment by nathanbraun** [comment]
vim-pandoc appears to be messing up my neovim buffers as well.  I'm using fzf.vim and anytime I open it to search for a file or open a new buffer vim-pandoc automatically opens another buffer.  Not positive it's related to this (I'm not purposely calling :Pandoc), but it's made vim-pandoc unusable for me.

**Comment by fmoralesc** [comment]
@nathanbraun That's weird, vim-pandoc only opens a new buffer when `:Pandoc` is executed. What is the name of the buffer it supposedly open in your case? Do you have automatic execution set up?

**Comment by fmoralesc** [comment]
By the way, @fflores97 I made the pandoc-execute take minimal space. It will still open, but only take 1 row of the window. I will make it configurable later.

**Comment by nathanbraun** [comment]
@fmoralesc it doesn't have a name, it's "[No Name]"

I don't have automatic execution setup, I really don't have any configuration, just the defaults.  I've only just started using it.

Looking at this more, I don't think it's related to the this same issue, but neovim + buffer problems caught my eye.  I can open a new issue if you'd like.

What's basically happening is:

1. I open up my file1.md file, everything is normal
2. Then I try do <leader>f to use fzf.vim to open up file2.md to open in a new buffer. 
- This is where things start going wrong.  First, the temporary buffer that fzf.vim opens up to look for a file is on top of the screen instead of the bottom line usual.  But I can use it to pick file2.md and open it.
3. Once I open it that now gives me  (1) a tiny buffer at the top of my screen with file2.md, (3) a buffer right below it with nothing in it, then (3) file1.md right below that in it's own buffer, then (4) file1.md again in another split view on my buffer.
- so all in all, 4 splits, one tiny one with file2, one blank one, and two with file1.md
- this is contrary to what i'd expect which is my two files open in separate buffers with just a view on file2

The only other buffer plugin I have besides fzf.vim is minibufexpl.vim which normally gives me a list of all my buffers at the top of the screen.

Let me know if you'd like me to make this a separate issue.

**Comment by fmoralesc** [comment]
@nathanbraun I think this is a separate issue, and it might have more to do with one of the other plugins (my guess is minibufexpl, because of the layout that you describe, with the tiny buffer on top). My suggestion would be to check if the problem exists also if you disable vim-pandoc. By the way, are you using vim or neovim?

**Comment by daviewales** [comment]
Would it be possible to automatically close the buffer window (or even better, never open it) if the text contained in the window is '[Process exited 0]'?

**Comment by fmoralesc** [comment]
@daviewales I just pushed this behavior now ;) 

I also made it so that if there are errors, the terminal will be tall enough so that they will be displayed. It turns out that if you minimize the size of the terminal, the output of commands run by nvim gets swallowed.

**Comment by nickwynja** [comment]
@fmoralesc This is a nice improvement. Thanks!

I expected some sort of affirmative feedback that Pandoc was running rather than just a blank buffer. I think adding something like `vim.command("put='Running pandoc...\r'")` (after the `call termopen` seems to work nicely) would give some good feedback that it's running properly. Then the error just gets appended to the buffer below the "running" message.

I can open up a PR if you'd like.

**Comment by fmoralesc** [comment]
> I expected some sort of affirmative feedback that Pandoc was running rather than just a blank buffer.

I guess I didn't see the need, because the buffer is titled `pandoc-execute`, which suffices for me (I have the statusline enabled, so I see it every time). We could make the status line include the more natural looking `Running pandoc...` string.

> I can open up a PR if you'd like.
Feel free, then I can test it.

**Comment by nickwynja** [comment]
@fmoralesc See PR #348. Thanks!

**Comment by alerque** [comment]
A quick review suggests this is token care of now that I've merged #348 (along with prior changes). If anybody thinks the current state is not satisfactory please ping me here and I'll re-open this for review.

**Comment by daviewales** [comment]
Hooray!

![vim-pandoc](https://user-images.githubusercontent.com/2499066/73537378-6f2bdb00-447c-11ea-8374-9b659f60256c.gif)
