### ISSUE TITLE
Pass the date in the :Pandoc command?

### ISSUE THREAD

**Issue by benfrain** [vim-pandoc/vim-pandoc#369]
Sorry — first time user! Just wondering how I could pass the current date into the command?

For example, trying something like this doesn't work: 

`:Pandoc --template discuss.html -s --metadata date="date -u '+%Y-%m-%d'"`

**Comment by alerque** [comment]
If you just refrain from setting the date value at all Pandoc will automatically fill it for you.

The answer to the question you asked is a bit more involved because you need some layers of shell quoting and escaping to run a command from vim, get the value, and place it in the command to run.

**Comment by benfrain** [comment]
Hi @alerque sorry, to be clear, do you mean I just pass a blank value `date=“”` or just don’t add the metadata at all?

**Comment by fmoralesc** [comment]
No need to pass the metadata at all. If you need to give a *specific* date, the best way is probably to adjust the template and pass a custom variable. And if you need to shell out to get the date, then there's the problem that @alerque mentioned, in which case it might be better to use have a Makefile and using something like `panzer`.

**Comment by benfrain** [comment]
Hmmm, I'm running `:Pandoc --template discuss.html -s -o myFolder/index.html` so no metadata at all.

In my template I have ${date} where I would like the date to be interpolated.

However, the output file is blank where the date should be — what am I doing wrong?

**Comment by fmoralesc** [comment]
It turns out that the `html` output does not add dates unless it is explicitly given. A workaround is to execute the `:Pandoc` command indirectly:

```vim
exe 'Pandoc! html -s --metadata date='.strftime('%Y-%m-%d')
```

A more robust solution would be to pass function calls to vim, or to introduce some form of subcommands, but that would probably be a lot of work and make the codebase less maintainable.

**Comment by benfrain** [comment]
Perfect thanks! Even opens resultant file in a browser window!

**Comment by alerque** [comment]
I stand corrected, I thought this was a different value you were trying to set, not the date metadata field. That doesn't get set if it doesn't exist in meta data.

I would actually suggest tackling this sort of thing in your document rather than in the editor. If you want a document that always updates the meta data date on build, then what you should probably use is a Pandoc filter. There are several languages you can use for this, but the easiest built in one is Lua. You would write a filter file, say `add_date.lua` with this:

```lua
function Meta(meta)
	if not meta.date then
		meta.date = os.date("%Y-%m-%d")
	end
	return meta
end
```

You could also name it `<document_name>.lua` if you plan on keeping it side by side with your document so it is clear it goes with it. Then invoke it like so:

```vim
:Pandoc --template discuss.html -s --lua-filter add_date.lua
```

**Comment by benfrain** [comment]
@alerque thanks, that looks pretty interesting. Will definitely have a play with that as I imagine I'll quickly get to a point I need to introduce more control flow for title etc
